const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
export function validateReviews(raw){
 const r=raw?.rating;if(!r||r.source!=='VERIFIED_ORDER_REVIEWS'||!Number.isSafeInteger(r.count)||r.count<0||r.count>10000000||!Array.isArray(raw.reviews)||raw.reviews.length>20||(r.count===0?r.average!==null:typeof r.average!=='number'||!Number.isFinite(r.average)||r.average<1||r.average>5)||raw.reviews.length>r.count)throw Error('REVIEWS_INVALID');
 return {rating:{source:r.source,count:r.count,average:r.average},reviews:raw.reviews.map(row=>{
  if(!row||!UUID.test(row.id)||row.verifiedCustomer!==true||!Number.isInteger(row.stars)||row.stars<1||row.stars>5||typeof row.firstName!=='string'||!row.firstName.trim()||row.firstName.length>80||typeof row.comment!=='string'||row.comment.length>3000||typeof row.submittedAt!=='string'||row.submittedAt.length>40||Number.isNaN(Date.parse(row.submittedAt))||(row.usedOn!==null&&(typeof row.usedOn!=='string'||row.usedOn.length>40||Number.isNaN(Date.parse(row.usedOn)))))throw Error('REVIEW_INVALID');
  return {id:row.id,stars:row.stars,firstName:row.firstName,comment:row.comment,usedOn:row.usedOn,submittedAt:row.submittedAt,verifiedCustomer:true};
 })};
}
export const REVIEW_COPY={
 en:{none:'No verified reviews yet',unavailable:'Customer reviews are currently unavailable.',verified:'Verified customer',count:'reviews',title:'Share your experience',intro:'Your feedback goes to NOODY for review. Only approved feedback with your permission appears publicly.',name:'First name',stars:'Rating',comment:'Your feedback',date:'Used on (optional)',consent:'I agree to publish my first name, rating and feedback after moderation.',submit:'Submit feedback',thanks:'Thank you. Your feedback has been received for review.',invalid:'Use the review link sent for your completed NOODY order.',failed:'Could not submit. Check your fields; the link may have expired or already been used.'},
 ml:{none:'Verified reviews ഇതുവരെ ഇല്ല',unavailable:'Customer reviews ഇപ്പോൾ ലഭ്യമല്ല.',verified:'Verified customer',count:'reviews',title:'നിങ്ങളുടെ അനുഭവം പങ്കുവെക്കൂ',intro:'Feedback ആദ്യം NOODY review ചെയ്യും. നിങ്ങളുടെ അനുമതിയുള്ള approved feedback മാത്രം public ആയി കാണിക്കും.',name:'ആദ്യ പേര്',stars:'Rating',comment:'നിങ്ങളുടെ അഭിപ്രായം',date:'ഉപയോഗിച്ച തീയതി (optional)',consent:'Review കഴിഞ്ഞ് എന്റെ ആദ്യ പേരും rating-ഉം അഭിപ്രായവും public ആയി കാണിക്കാൻ സമ്മതിക്കുന്നു.',submit:'Feedback അയക്കൂ',thanks:'നന്ദി. നിങ്ങളുടെ feedback review ചെയ്യാൻ ലഭിച്ചു.',invalid:'പൂർത്തിയായ NOODY order-നു ലഭിച്ച review link ഉപയോഗിക്കൂ.',failed:'അയക്കാനായില്ല. വിവരങ്ങൾ പരിശോധിക്കൂ; link expire ആയിരിക്കാം അല്ലെങ്കിൽ നേരത്തെ ഉപയോഗിച്ചിരിക്കാം.'},
 hi:{none:'अभी सत्यापित समीक्षाएं नहीं हैं',unavailable:'ग्राहकों की समीक्षाएं अभी उपलब्ध नहीं हैं।',verified:'सत्यापित ग्राहक',count:'समीक्षाएं',title:'अपना अनुभव बताएं',intro:'आपकी प्रतिक्रिया पहले NOODY की समीक्षा के लिए जाएगी। आपकी अनुमति से केवल स्वीकृत प्रतिक्रिया सार्वजनिक होगी।',name:'पहला नाम',stars:'रेटिंग',comment:'आपकी प्रतिक्रिया',date:'इस्तेमाल की तारीख (वैकल्पिक)',consent:'समीक्षा के बाद मेरा पहला नाम, रेटिंग और प्रतिक्रिया प्रकाशित करने की अनुमति देता/देती हूं।',submit:'प्रतिक्रिया भेजें',thanks:'धन्यवाद। आपकी प्रतिक्रिया समीक्षा के लिए मिल गई है।',invalid:'अपने पूरे हुए NOODY ऑर्डर के लिए भेजे गए समीक्षा लिंक का उपयोग करें।',failed:'भेज नहीं सके। जानकारी जांचें; लिंक समाप्त या पहले इस्तेमाल हो सकता है।'}
};
