import {loadWebsiteData,localize,visibleItems,ISLAND_NAMES,pageLink,validateWebsiteData} from './website-data.mjs';import {itemLink,websiteEnquiry,readLanguage,rememberLanguage} from './listing.mjs';import {loadDesign} from './design.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={data:null,page:null,language:readLanguage(),island:'',kind:'SERVICE',assets:{}};const $=id=>document.getElementById(id),src=v=>state.assets?.[v]||v;
function widthClass(w){return 'block-'+(w||'wide');}
function style(block){const s=block.style;return 'background:'+esc(s.background||'transparent')+';color:'+esc(s.textColor||'inherit')+';text-align:'+esc(s.align)+';padding:'+s.padding+'px;border-radius:'+s.radius+'px';}
function header(){const d=state.data,lang=state.language,brand=$('brand'),nav=$('navlinks');brand.innerHTML=(d.brand.logo?'<img src="'+esc(src(d.brand.logo))+'" alt="">':'')+esc(d.brand.name);nav.innerHTML=d.pages.filter(p=>p.active&&p.showInNav).map(p=>'<a href="'+esc(pageLink(p,location.href))+'">'+esc(localize(p.navLabel,lang,localize(p.title,lang,p.slug)))+'</a>').join('');$('headerWa').href=websiteEnquiry(d.whatsappNumber,null,null,lang,location.href);$('footerText').textContent=localize(d.footer.text,lang,localize(d.brand.tagline,lang,''));$('privacyLink').hidden=!d.footer.showPrivacy;}
function blockHead(b,tag='h2'){return '<div class="block-head">'+(localize(b.eyebrow,state.language)?'<div class="eyebrow">'+esc(localize(b.eyebrow,state.language))+'</div>':'')+(localize(b.title,state.language)?'<'+tag+'>'+esc(localize(b.title,state.language))+'</'+tag+'>':'')+(localize(b.body,state.language)?'<p>'+esc(localize(b.body,state.language))+'</p>':'')+'</div>';}
function cta(b){const label=localize(b.ctaLabel,state.language);if(!label||b.ctaAction==='none')return'';let href='#';if(b.ctaAction==='whatsapp')href=websiteEnquiry(state.data.whatsappNumber,b.islandCode||null,null,state.language,location.href);if(b.ctaAction==='page'){const p=state.data.pages.find(x=>x.slug===b.ctaTarget&&x.active);href=p?pageLink(p,location.href):'#';}if(b.ctaAction==='url')href=b.ctaTarget||'#';return '<div class="block-actions"><a class="cta" '+(b.ctaAction==='whatsapp'||b.ctaAction==='url'?'target="_blank" rel="noopener noreferrer" ':'')+'href="'+esc(href)+'">'+esc(label)+'</a></div>';}
function hero(b){const image=b.image?'background-image:url('+JSON.stringify(src(b.image))+')':'';return '<section class="page-block hero-block '+widthClass(b.style.width)+'" style="'+style(b)+';'+image+'"><div class="block-inner shell"><div class="hero-copy">'+blockHead(b,'h1')+cta(b)+'</div></div></section>';}
function textBlock(b){return '<section class="page-block text-block '+widthClass(b.style.width)+'" style="'+style(b)+'"><div class="block-inner">'+blockHead(b)+cta(b)+'</div></section>';}
function imageText(b){const img=b.image?'<img class="block-image" src="'+esc(src(b.image))+'" alt="'+esc(localize(b.title,state.language,'Image'))+'">':'';const reverse=b.variant==='image-left'?' reverse':'';return '<section class="page-block image-text-block '+widthClass(b.style.width)+'" style="'+style(b)+'"><div class="block-inner image-text-grid'+reverse+'"><div>'+blockHead(b)+cta(b)+'</div>'+img+'</div></section>';}
function gallery(b){return '<section class="page-block gallery-block '+widthClass(b.style.width)+'" style="'+style(b)+'"><div class="block-inner">'+blockHead(b)+'<div class="gallery-grid" style="--cols:'+b.columns+'">'+b.images.map(x=>'<img loading="lazy" src="'+esc(src(x.src))+'" alt="'+esc(localize(x.alt,state.language,''))+'">').join('')+'</div>'+cta(b)+'</div></section>';}
function itemCards(items){return items.map(i=>{const cover=i.photos[0],title=localize(i.title,state.language,i.name),summary=localize(i.summary,state.language,i.category);return '<article class="item-card">'+(cover?'<img loading="lazy" src="'+esc(src(cover.src))+'" alt="'+esc(localize(cover.alt,state.language,title))+'">':'')+'<div class="item-body"><div class="eyebrow">'+esc(ISLAND_NAMES[i.islandCode]+' · '+i.category)+'</div><h3>'+esc(title)+'</h3><p>'+esc(summary)+'</p><div class="item-actions"><a class="link" href="'+esc(itemLink(i,location.href))+'">Details</a><a class="link" target="_blank" rel="noopener noreferrer" href="'+esc(websiteEnquiry(state.data.whatsappNumber,i.islandCode,i,state.language,location.href))+'">WhatsApp</a></div></div></article>';}).join('');}
function featured(b){const items=visibleItems(state.data,{island:b.islandCode,kind:b.itemKind,category:b.category}).slice(0,b.limit);return '<section class="page-block featured-block '+widthClass(b.style.width)+'" style="'+style(b)+'"><div class="block-inner">'+blockHead(b)+'<div class="item-grid" style="--cols:'+b.columns+'">'+itemCards(items)+'</div>'+cta(b)+'</div></section>';}
function reviewBlock(b){let reviews=[];for(const i of state.data.items){if(b.itemKind!=='ALL'&&i.kind!==b.itemKind)continue;if(b.islandCode&&i.islandCode!==b.islandCode)continue;for(const r of i.reviews)reviews.push({...r,item:i});}reviews=reviews.slice(0,b.limit);return '<section class="page-block review-block '+widthClass(b.style.width)+'" style="'+style(b)+'"><div class="block-inner">'+blockHead(b)+'<div class="review-grid" style="--cols:'+b.columns+'">'+reviews.map(r=>'<article class="review-card"><div class="stars">'+'★'.repeat(r.stars)+'☆'.repeat(5-r.stars)+'</div><p>'+esc(r.comment)+'</p><strong>'+esc(r.firstName)+'</strong><div class="status">'+(r.verified?'Verified customer · ':'')+esc(localize(r.item.title,state.language,r.item.name))+'</div></article>').join('')+'</div>'+cta(b)+'</div></section>';}
function faq(b){return '<section class="page-block faq-block '+widthClass(b.style.width)+'" style="'+style(b)+'"><div class="block-inner">'+blockHead(b)+b.faqs.map(x=>'<details class="faq-item"><summary>'+esc(localize(x.question,state.language))+'</summary><p>'+esc(localize(x.answer,state.language))+'</p></details>').join('')+cta(b)+'</div></section>';}
function whatsappCta(b){return '<section class="page-block cta-block '+widthClass(b.style.width)+'" style="'+style(b)+'"><div class="block-inner">'+blockHead(b)+ (cta({...b,ctaAction:'whatsapp',ctaLabel:b.ctaLabel.en||b.ctaLabel.ml||b.ctaLabel.hi?b.ctaLabel:{en:'Enquire on WhatsApp',ml:'',hi:''}}))+'</div></section>';}
function spacer(b){return '<div class="page-block spacer-block" style="height:'+b.height+'px"></div>';}
function islandSelector(b){const islands=state.data.islands.filter(i=>i.active),cards=islands.map(i=>'<button class="island-card" data-select-island="'+esc(i.code)+'">'+(i.image?'<img src="'+esc(src(i.image))+'" alt="'+esc(localize(i.title,state.language,i.name))+'">':'')+'<span class="island-card-body"><strong>'+esc(localize(i.title,state.language,i.name))+'</strong><small>'+esc(localize(i.description,state.language,''))+'</small></span></button>').join('');return '<section class="page-block island-block '+widthClass(b.style.width)+'" style="'+style(b)+'"><div class="block-inner">'+blockHead(b)+'<div class="island-grid" style="--cols:'+b.columns+'">'+cards+'</div><div class="island-results" id="islandResults"></div></div></section>';}
function bindIsland(){document.querySelectorAll('[data-select-island]').forEach(btn=>btn.onclick=()=>{state.island=btn.dataset.selectIsland;state.kind='SERVICE';renderIslandResults();});}
function renderIslandResults(){const box=$('islandResults');if(!box)return;const kindButtons='<div class="kind-picker"><button data-kind="SERVICE" class="'+(state.kind==='SERVICE'?'active':'')+'">Services</button><button data-kind="PRODUCT" class="'+(state.kind==='PRODUCT'?'active':'')+'">Products</button></div>',items=visibleItems(state.data,{island:state.island,kind:state.kind});box.innerHTML='<h2>'+esc(ISLAND_NAMES[state.island])+'</h2>'+kindButtons+'<div class="item-grid" style="--cols:3">'+itemCards(items)+'</div>';box.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{state.kind=b.dataset.kind;renderIslandResults();});}
function renderBlock(b){if(!b.active)return'';return ({hero,islandSelector,text:textBlock,imageText,gallery,featuredItems:featured,reviews:reviewBlock,faq,whatsappCta,spacer})[b.type](b);}
function syncLanguageButtons(){document.querySelectorAll('[data-language]').forEach(b=>{b.classList.toggle('active',b.dataset.language===state.language);b.setAttribute('aria-pressed',String(b.dataset.language===state.language));});const select=$('language');if(select)select.value=state.language;}function render(){header();syncLanguageButtons();document.documentElement.lang=state.language;document.title=localize(state.page.title,state.language,state.data.brand.name)+' | '+state.data.brand.name;const meta=document.querySelector('meta[name=description]');if(meta)meta.content=localize(state.page.metaDescription,state.language,'');$('pageRoot').innerHTML=state.page.blocks.map(renderBlock).join('')||'<div class="missing"><h1>Page is empty</h1></div>';bindIsland();}
export async function startPage(slug='home'){const studioPreview=new URLSearchParams(location.search).get('studio_preview')==='1'&&window.parent!==window;try{state.data=await loadWebsiteData();state.page=state.data.pages.find(p=>p.slug===slug&&p.active)||state.data.pages.find(p=>p.slug==='home');if(!state.page)throw Error('PAGE_NOT_FOUND');$('language').value=state.language;$('language').onchange=e=>{state.language=e.target.value;rememberLanguage(state.language);render();};document.querySelectorAll('[data-language]').forEach(b=>b.onclick=()=>{state.language=b.dataset.language;rememberLanguage(state.language);render();});render();await loadDesign();document.body.dataset.state=studioPreview?'preview':'ready';if(studioPreview){window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==window.parent||e.data?.type!=='NOODY_STUDIO_PAGE_PREVIEW')return;try{const next=validateWebsiteData(e.data.data),page=next.pages.find(p=>p.id===e.data.pageId);if(!page)throw Error('PAGE_NOT_FOUND');state.data=next;state.page=page;state.assets=e.data.assets||{};state.language=['en','ml','hi'].includes(e.data.language)?e.data.language:state.language;$('language').value=state.language;render();window.parent.postMessage({type:'NOODY_STUDIO_PAGE_APPLIED'},location.origin);}catch{}});window.parent.postMessage({type:'NOODY_STUDIO_PAGE_READY'},location.origin);}}catch(e){document.body.dataset.state='unavailable';$('pageRoot').innerHTML='<div class="missing"><h1>Page unavailable</h1><p>'+esc(e.message)+'</p></div>';}}
