import {validateWebsiteData,blankPage,blankPageBlock,blankItem,BLOCK_TYPES,ISLAND_NAMES,localize,pageLink,photoUrl} from './website-data.mjs';import {itemLink} from './listing.mjs';import {makeZip} from './zip.mjs';import {DEFAULT_DESIGN,validateDesign} from './design.mjs';
const $=id=>document.getElementById(id),draftKey='noody.website.studio.pro.v2';let data,design=structuredClone(DEFAULT_DESIGN),assets={},selectedPage='',selectedItem='',previewReady=false,designPreviewReady=false,previewMode='page';
const langMap=()=>({en:'',ml:'',hi:''}),uuid=()=>crypto.randomUUID(),status=(m,e=false)=>{$('status').textContent=m;$('status').classList.toggle('error',e);};
function persist(){try{localStorage.setItem(draftKey,JSON.stringify({data,design,assets}));status('Auto-saved.');}catch{status('Draft updated. Browser storage is full; download soon.',true);}renderPreview();}function saveNow(scope='Website'){try{data=validateWebsiteData(data);design=validateDesign(design);localStorage.setItem(draftKey,JSON.stringify({data,design,assets}));status(scope+' saved ✓');renderPreview();return true;}catch(err){status('Cannot save: '+err.message,true);return false;}}
function tab(name){for(const b of document.querySelectorAll('[data-tab]'))b.classList.toggle('active',b.dataset.tab===name);for(const n of ['pages','items','media','design','settings'])$(n+'Tab').classList.toggle('hidden',n!==name);if(name==='media')renderMedia();if(name==='design')renderDesign();if(name==='settings')renderSettings();}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>tab(b.dataset.tab);
function mediaOptions(select,includeNone=true){const prior=select.value;select.replaceChildren();if(includeNone)select.add(new Option('No image',''));for(const m of data.media||[])select.add(new Option(localize(m.title,'en','Image')+' · '+m.src,m.src));if([...select.options].some(o=>o.value===prior))select.value=prior;}
async function compress(file){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('Use PNG/JPEG/WebP up to 10 MB.');const bmp=await createImageBitmap(file),scale=Math.min(1,1800/Math.max(bmp.width,bmp.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bmp.width*scale));canvas.height=Math.max(1,Math.round(bmp.height*scale));canvas.getContext('2d').drawImage(bmp,0,0,canvas.width,canvas.height);bmp.close();const blob=await new Promise(r=>canvas.toBlob(r,'image/webp',.84));if(!blob||blob.size>850000)throw Error('Image is too large after compression.');const url=await new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(blob);});return url;}
async function addUploadedMedia(files){for(const file of files){const src='./media/'+uuid()+'.webp';assets[src]=await compress(file);data.media.push({id:uuid(),src,title:{en:file.name.replace(/\.[^.]+$/,''),ml:'',hi:''}});}persist();renderMedia();}
function renderMedia(){const box=$('mediaGrid');box.replaceChildren();for(const m of data.media){const card=document.createElement('div');card.className='media-card';const img=document.createElement('img');img.src=assets[m.src]||m.src;const name=document.createElement('input');name.value=m.title.en||'';name.placeholder='Image name';name.oninput=()=>{m.title.en=name.value;persist();};const actions=document.createElement('div');actions.className='actions';const copy=document.createElement('button');copy.textContent='Copy path';copy.onclick=()=>navigator.clipboard?.writeText(m.src);const rm=document.createElement('button');rm.textContent='Remove';rm.className='danger';rm.onclick=()=>{data.media=data.media.filter(x=>x.id!==m.id);delete assets[m.src];persist();renderMedia();};actions.append(copy,rm);card.append(img,name,actions);box.append(card);}refreshMediaSelects();}
function refreshMediaSelects(){for(const s of [$('brandLogo'),$('itemMediaSelect')])if(s)mediaOptions(s);if(selectedPage)renderBlocks();if(selectedItem)renderItemPhotos();}

function pageById(){return data.pages.find(p=>p.id===selectedPage);}function pageHref(p){return pageLink(p,location.href);}
function renderPageList(){const box=$('pageList');box.replaceChildren();for(const p of data.pages){const e=document.createElement('div');e.className='entry'+(p.id===selectedPage?' active':'');e.innerHTML='<strong>'+escapeText(localize(p.title,'en',p.slug))+'</strong><div class="note">/'+escapeText(p.slug)+' · '+(p.active?'LIVE':'HIDDEN')+(p.showInNav?' · MENU':'')+'</div>';const actions=document.createElement('div');actions.className='actions';const edit=document.createElement('button');edit.textContent='Edit';edit.onclick=()=>selectPage(p.id);const up=document.createElement('button');up.textContent='↑';up.disabled=data.pages.indexOf(p)===0;up.onclick=()=>move(data.pages,data.pages.indexOf(p),-1,renderPageList);const down=document.createElement('button');down.textContent='↓';down.disabled=data.pages.indexOf(p)===data.pages.length-1;down.onclick=()=>move(data.pages,data.pages.indexOf(p),1,renderPageList);actions.append(edit,up,down);e.append(actions);box.append(e);}}
function selectPage(id){selectedPage=id;selectedItem='';const p=pageById();$('pageEditor').classList.remove('hidden');$('pageSlug').value=p.slug;$('pageSlug').disabled=p.slug==='home';$('pageActive').checked=p.active;$('pageNav').checked=p.showInNav;$('deletePage').disabled=p.slug==='home';renderPageLanguage();renderBlocks();$('openPageLink').href=pageHref(p);previewMode='page';loadPagePreview();renderPageList();}
function renderPageLanguage(){const p=pageById(),l=$('pageLanguage').value;if(!p)return;$('pageNavLabel').value=p.navLabel[l]||'';$('pageTitle').value=p.title[l]||'';$('pageMeta').value=p.metaDescription[l]||'';}
function blockLabel(type){return {hero:'Hero / Banner',islandSelector:'Island selector',text:'Text',imageText:'Image + Text',slideshow:'Slideshow / Gadget',gallery:'Gallery',featuredItems:'Services / Products grid',reviews:'Reviews',faq:'FAQ',whatsappCta:'WhatsApp CTA',spacer:'Spacer'}[type]||type;}
function move(list,i,d,rerender){const j=i+d;if(j<0||j>=list.length)return;[list[i],list[j]]=[list[j],list[i]];persist();rerender();}
function blockEditor(b,i,p){const d=document.createElement('div');d.className='block-card';const top=document.createElement('div');top.className='block-top';const name=document.createElement('span');name.className='block-type';name.textContent=(i+1)+'. '+blockLabel(b.type);const actions=document.createElement('div');actions.className='actions';for(const [txt,delta] of [['↑',-1],['↓',1]]){const x=document.createElement('button');x.textContent=txt;x.disabled=i+delta<0||i+delta>=p.blocks.length;x.onclick=()=>move(p.blocks,i,delta,renderBlocks);actions.append(x);}const hide=document.createElement('button');hide.textContent=b.active?'Hide':'Show';hide.onclick=()=>{b.active=!b.active;persist();renderBlocks();};const rm=document.createElement('button');rm.textContent='Remove';rm.className='danger';rm.onclick=()=>{p.blocks.splice(i,1);persist();renderBlocks();};actions.append(hide,rm);top.append(name,actions);d.append(top);if(b.type==='spacer'){const h=input('Height',b.height,'number');h.querySelector('input').oninput=e=>{b.height=Number(e.target.value)||80;persist();};d.append(h);return d;}
 const l=$('pageLanguage').value;d.append(input('Eyebrow',b.eyebrow[l]),input('Title',b.title[l]),textarea('Text / description',b.body[l],4));const inputs=d.querySelectorAll('input,textarea');inputs[0].oninput=e=>{b.eyebrow[l]=e.target.value;persist();};inputs[1].oninput=e=>{b.title[l]=e.target.value;persist();};inputs[2].oninput=e=>{b.body[l]=e.target.value;persist();};
 const styleRow=document.createElement('div');styleRow.className='row';const align=selectWrap('Text align',[['left','Left'],['center','Center'],['right','Right']],b.style.align),width=selectWrap('Width',[['full','Full'],['wide','Wide'],['normal','Normal'],['narrow','Narrow']],b.style.width);align.querySelector('select').onchange=e=>{b.style.align=e.target.value;persist();};width.querySelector('select').onchange=e=>{b.style.width=e.target.value;persist();};styleRow.append(align,width);d.append(styleRow);
 const colors=document.createElement('div');colors.className='row';const bg=input('Background color',b.style.background||'transparent'),tc=input('Text color',b.style.textColor||'');bg.querySelector('input').placeholder='#ffffff or transparent';tc.querySelector('input').placeholder='#15372e';bg.querySelector('input').onchange=e=>{b.style.background=e.target.value||'transparent';persist();};tc.querySelector('input').onchange=e=>{b.style.textColor=e.target.value;persist();};colors.append(bg,tc);d.append(colors);
 const spacing=document.createElement('div');spacing.className='row';const pad=input('Inner padding',b.style.padding,'number'),radius=input('Corner radius',b.style.radius,'number');pad.querySelector('input').min='0';pad.querySelector('input').max='140';radius.querySelector('input').min='0';radius.querySelector('input').max='80';pad.querySelector('input').oninput=e=>{b.style.padding=Math.max(0,Math.min(140,Number(e.target.value)||0));persist();};radius.querySelector('input').oninput=e=>{b.style.radius=Math.max(0,Math.min(80,Number(e.target.value)||0));persist();};spacing.append(pad,radius);d.append(spacing);
 if(['hero','imageText'].includes(b.type)){const imageSel=selectWrap('Main image',mediaPairs(),b.image);imageSel.querySelector('select').onchange=e=>{b.image=e.target.value;persist();};d.append(imageSel);}
 if(b.type==='hero'){const focus=document.createElement('div');focus.className='row';const x=input('Background X %',b.style.bgX,'number'),y=input('Background Y %',b.style.bgY,'number');for(const w of [x,y]){const el=w.querySelector('input');el.min='0';el.max='100';}x.querySelector('input').oninput=e=>{b.style.bgX=Math.max(0,Math.min(100,Number(e.target.value)||0));persist();};y.querySelector('input').oninput=e=>{b.style.bgY=Math.max(0,Math.min(100,Number(e.target.value)||0));persist();};focus.append(x,y);d.append(focus);
 const heroRow=document.createElement('div');heroRow.className='row';const fit=selectWrap('Background fit',[['cover','Cover'],['contain','Contain'],['auto','Original / auto']],b.style.bgSize),overlay=input('Overlay darkness %',b.style.overlay,'number');fit.querySelector('select').onchange=e=>{b.style.bgSize=e.target.value;persist();};overlay.querySelector('input').min='0';overlay.querySelector('input').max='90';overlay.querySelector('input').oninput=e=>{b.style.overlay=Math.max(0,Math.min(90,Number(e.target.value)||0));persist();};heroRow.append(fit,overlay);d.append(heroRow);
 const sizeRow=document.createElement('div');sizeRow.className='row';const height=input('Hero height px',b.style.minHeight,'number'),contentWidth=input('Text content width px',b.style.contentWidth,'number');height.querySelector('input').min='120';height.querySelector('input').max='1000';contentWidth.querySelector('input').min='260';contentWidth.querySelector('input').max='1400';height.querySelector('input').oninput=e=>{b.style.minHeight=Math.max(120,Math.min(1000,Number(e.target.value)||460));persist();};contentWidth.querySelector('input').oninput=e=>{b.style.contentWidth=Math.max(260,Math.min(1400,Number(e.target.value)||700));persist();};sizeRow.append(height,contentWidth);d.append(sizeRow);}
 if(['gallery','slideshow'].includes(b.type)){const add=document.createElement('div');add.className='actions';const sel=document.createElement('select');for(const [v,n] of mediaPairs())sel.add(new Option(n,v));const btn=document.createElement('button');btn.textContent='Add image';btn.onclick=()=>{if(sel.value)b.images.push({src:sel.value,alt:langMap()});persist();renderBlocks();};add.append(sel,btn);d.append(add);for(const [gi,g] of b.images.entries()){const row=document.createElement('div');row.className='entry';row.textContent=localize(g.alt,l,g.src);const rm=document.createElement('button');rm.textContent='Remove';rm.onclick=()=>{b.images.splice(gi,1);persist();renderBlocks();};row.append(rm);d.append(row);}}
 if(b.type==='featuredItems'){const r=document.createElement('div');r.className='row';const kind=selectWrap('Show',[['ALL','All'],['SERVICE','Services'],['PRODUCT','Products']],b.itemKind),island=selectWrap('Island',[['','All islands'],...Object.entries(ISLAND_NAMES).map(([v,n])=>[v,n])],b.islandCode);kind.querySelector('select').onchange=e=>{b.itemKind=e.target.value;persist();};island.querySelector('select').onchange=e=>{b.islandCode=e.target.value;persist();};r.append(kind,island);d.append(r);const cat=input('Category filter (optional)',b.category);cat.querySelector('input').oninput=e=>{b.category=e.target.value;persist();};d.append(cat);}
 if(b.type==='reviews'){const r=document.createElement('div');r.className='row';const kind=selectWrap('Reviews for',[['ALL','All'],['SERVICE','Services'],['PRODUCT','Products']],b.itemKind),limit=input('Maximum reviews',b.limit,'number');kind.querySelector('select').onchange=e=>{b.itemKind=e.target.value;persist();};limit.querySelector('input').oninput=e=>{b.limit=Math.max(1,Math.min(100,Number(e.target.value)||8));persist();};r.append(kind,limit);d.append(r);}
 if(b.type==='faq'){const add=document.createElement('button');add.textContent='+ FAQ';add.onclick=()=>{b.faqs.push({id:uuid(),question:langMap(),answer:langMap()});persist();renderBlocks();};d.append(add);for(const [fi,f] of b.faqs.entries()){const q=input('Question',f.question[l]),a=textarea('Answer',f.answer[l],3);q.querySelector('input').oninput=e=>{f.question[l]=e.target.value;persist();};a.querySelector('textarea').oninput=e=>{f.answer[l]=e.target.value;persist();};const rm=document.createElement('button');rm.textContent='Remove FAQ';rm.onclick=()=>{b.faqs.splice(fi,1);persist();renderBlocks();};const wrap=document.createElement('div');wrap.className='entry';wrap.append(q,a,rm);d.append(wrap);}}
 if(b.type!=='islandSelector'&&b.type!=='gallery'&&b.type!=='slideshow'){const ctaTitle=document.createElement('h3');ctaTitle.textContent='Button / CTA';d.append(ctaTitle);const ctaRow=document.createElement('div');ctaRow.className='row';const action=selectWrap('Action',[['none','No button'],['whatsapp','WhatsApp'],['page','Another page'],['url','External URL']],b.ctaAction),label=input('Button text',b.ctaLabel[l]);action.querySelector('select').onchange=e=>{b.ctaAction=e.target.value;persist();};label.querySelector('input').oninput=e=>{b.ctaLabel[l]=e.target.value;persist();};ctaRow.append(action,label);d.append(ctaRow);const target=input('Target page slug / HTTPS URL',b.ctaTarget);target.querySelector('input').oninput=e=>{b.ctaTarget=e.target.value;persist();};d.append(target);}
 return d;}
function renderBlocks(){const p=pageById(),box=$('pageBlocks');if(!p)return;box.replaceChildren();p.blocks.forEach((b,i)=>box.append(blockEditor(b,i,p)));}
function mediaPairs(){return [['','No image'],...(data.media||[]).map(m=>[m.src,localize(m.title,'en','Image')])];}

function itemById(){return data.items.find(i=>i.id===selectedItem);}function renderItemList(){const box=$('itemList');box.replaceChildren();for(const i of data.items){const e=document.createElement('div');e.className='entry'+(i.id===selectedItem?' active':'');e.innerHTML='<strong>'+(i.kind==='SERVICE'?'🌊 ':'🎁 ')+escapeText(localize(i.title,'en',i.name))+'</strong><div class="note">'+escapeText(ISLAND_NAMES[i.islandCode]+' · '+i.category+' · '+(i.active?'LIVE':'HIDDEN'))+'</div>';const b=document.createElement('button');b.textContent='Edit';b.onclick=()=>selectItem(i.id);e.append(b);box.append(e);}}
function selectItem(id){selectedItem=id;selectedPage='';const i=itemById();$('itemEditor').classList.remove('hidden');$('itemKind').value=i.kind;$('itemIsland').value=i.islandCode;$('itemName').value=i.name;$('itemCategory').value=i.category;$('itemActive').checked=i.active;renderItemLanguage();renderItemPhotos();renderDetails();renderItemSections();renderReviews();const href=itemLink(i,location.href);$('itemLink').value=href;$('openItemLink').href=href;previewMode='item';loadItemPreview();renderItemList();}
function renderItemLanguage(){const i=itemById(),l=$('itemLanguage').value;if(!i)return;i.categoryLabel??={en:i.category||'',ml:'',hi:''};i.priceLabel??={en:i.priceText||'',ml:'',hi:''};i.availabilityLabel??={en:i.availabilityText||'',ml:'',hi:''};$('itemTitle').value=i.title[l]||'';$('itemCategoryLabel').value=i.categoryLabel[l]||'';$('itemPriceLabel').value=i.priceLabel[l]||'';$('itemAvailabilityLabel').value=i.availabilityLabel[l]||'';$('itemSummary').value=i.summary[l]||'';$('itemDescription').value=i.description[l]||'';renderItemPhotos();renderDetails();renderItemSections();renderReviews();}
function renderItemPhotos(){const i=itemById(),box=$('itemPhotos');if(!i)return;box.replaceChildren();mediaOptions($('itemMediaSelect'));const l=$('itemLanguage').value;i.photos.forEach((p,n)=>{p.alt??=langMap();const e=document.createElement('div');e.className='entry';e.innerHTML='<div class="note">'+escapeText(p.src)+'</div>';const alt=input('Photo description / alt text ('+l+')',p.alt[l]||'');alt.querySelector('input').oninput=x=>{p.alt[l]=x.target.value;persist();};const a=document.createElement('div');a.className='actions';const cover=document.createElement('button');cover.textContent=n?'Make cover':'Cover';cover.disabled=!n;cover.onclick=()=>{i.photos.splice(n,1);i.photos.unshift(p);persist();renderItemPhotos();};const rm=document.createElement('button');rm.textContent='Remove';rm.onclick=()=>{i.photos.splice(n,1);persist();renderItemPhotos();};a.append(cover,rm);e.append(alt,a);box.append(e);});}
function renderDetails(){const i=itemById(),box=$('itemDetails');if(!i)return;box.replaceChildren();const l=$('itemLanguage').value;i.details.forEach((d,n)=>{const e=document.createElement('div');e.className='entry';const lab=input('Label',d.label[l]),val=textarea('Value',d.value[l],2);lab.querySelector('input').oninput=x=>{d.label[l]=x.target.value;persist();};val.querySelector('textarea').oninput=x=>{d.value[l]=x.target.value;persist();};const rm=document.createElement('button');rm.textContent='Remove';rm.onclick=()=>{i.details.splice(n,1);persist();renderDetails();};e.append(lab,val,rm);box.append(e);});}
function renderItemSections(){const i=itemById(),box=$('itemSections');if(!i)return;box.replaceChildren();const l=$('itemLanguage').value;i.blocks.forEach((b,n)=>{const e=document.createElement('div');e.className='entry';const style=selectWrap('Style',[['section','Normal'],['highlight','Highlight'],['note','Note / warning'],['steps','Steps / itinerary']],b.style),title=input('Title',b.title[l]),body=textarea('Content',b.body[l],4);style.querySelector('select').onchange=x=>{b.style=x.target.value;persist();};title.querySelector('input').oninput=x=>{b.title[l]=x.target.value;persist();};body.querySelector('textarea').oninput=x=>{b.body[l]=x.target.value;persist();};const rm=document.createElement('button');rm.textContent='Remove';rm.onclick=()=>{i.blocks.splice(n,1);persist();renderItemSections();};e.append(style,title,body,rm);box.append(e);});}
function renderReviews(){const i=itemById(),box=$('itemReviews');if(!i)return;box.replaceChildren();const l=$('itemLanguage').value;i.reviews.forEach((r,n)=>{r.commentText??={en:r.comment||'',ml:'',hi:''};const e=document.createElement('div');e.className='entry review';const row=document.createElement('div');row.className='row';const name=input('First name',r.firstName),stars=selectWrap('Rating',[1,2,3,4,5].map(x=>[String(x),x+' / 5']),String(r.stars));name.querySelector('input').oninput=x=>{r.firstName=x.target.value;persist();};stars.querySelector('select').onchange=x=>{r.stars=Number(x.target.value);persist();};row.append(name,stars);const comment=textarea('Review text ('+l+')',r.commentText[l]||'',3);comment.querySelector('textarea').oninput=x=>{r.commentText[l]=x.target.value;if(l==='en')r.comment=x.target.value;persist();};const verified=document.createElement('label');verified.innerHTML='<input type="checkbox"> Verified customer';verified.querySelector('input').checked=r.verified;verified.querySelector('input').onchange=x=>{r.verified=x.target.checked;persist();};const rm=document.createElement('button');rm.textContent='Remove review';rm.onclick=()=>{i.reviews.splice(n,1);persist();renderReviews();};e.append(row,comment,verified,rm);box.append(e);});}

function renderDesign(){
 design=validateDesign(design);
 const colorMap={designAccent:'accent',designInk:'ink',designBackground:'background',designMuted:'muted',designHeader:'header',designCard:'card',designBorder:'border'};
 for(const [id,key] of Object.entries(colorMap))$(id).value=design.colors[key];
 $('designFont').value=design.font;$('designAnimations').checked=design.animations;
 const ui=design.ui;
 const values={designBodySize:ui.bodySize,designH1Size:ui.h1Size,designH2Size:ui.h2Size,designHeaderHeight:ui.headerHeight,designLogoWidth:ui.logoWidth,designNavGap:ui.navGap,designContainerWidth:ui.containerWidth,designSectionGap:ui.sectionGap,designButtonRadius:ui.buttonRadius,designCardRadius:ui.cardRadius};
 for(const [id,value] of Object.entries(values)){if($(id))$(id).value=String(value);const out=$(id+'Value');if(out)out.textContent=value+' px';}
 $('designHeaderSticky').checked=ui.headerSticky;$('designHeaderLayout').value=ui.headerLayout;$('designLanguageStyle').value=ui.languageStyle;$('designButtonWeight').value=String(ui.buttonWeight);$('designCardShadow').value=ui.cardShadow;
}
function renderSettings(){const l=$('settingsLanguage').value;$('brandName').value=data.brand.name;$('brandTagline').value=data.brand.tagline[l]||'';mediaOptions($('brandLogo'));$('brandLogo').value=data.brand.logo||'';$('whatsappNumber').value=data.whatsappNumber;$('footerText').value=data.footer.text[l]||'';$('showPrivacy').checked=data.footer.showPrivacy;const box=$('islandSettings');box.replaceChildren();for(const island of data.islands){const e=document.createElement('div');e.className='entry';const active=document.createElement('label');active.innerHTML='<input type="checkbox"> '+ISLAND_NAMES[island.code]+' active';active.querySelector('input').checked=island.active;active.querySelector('input').onchange=x=>{island.active=x.target.checked;if(!island.active)for(const i of data.items.filter(y=>y.islandCode===island.code))i.active=false;persist();};const title=input('Display title',island.title[l]||ISLAND_NAMES[island.code]),desc=textarea('Description',island.description[l]||'',2),img=selectWrap('Island image',mediaPairs(),island.image||'');title.querySelector('input').oninput=x=>{island.title[l]=x.target.value;persist();};desc.querySelector('textarea').oninput=x=>{island.description[l]=x.target.value;persist();};img.querySelector('select').onchange=x=>{island.image=x.target.value;persist();};e.append(active,title,desc,img);box.append(e);}}

function input(label,value='',type='text'){const l=document.createElement('label');l.textContent=label;const x=document.createElement('input');x.type=type;x.value=value??'';l.append(x);return l;}function textarea(label,value='',rows=3){const l=document.createElement('label');l.textContent=label;const x=document.createElement('textarea');x.rows=rows;x.value=value??'';l.append(x);return l;}function selectWrap(label,pairs,value=''){const l=document.createElement('label');l.textContent=label;const s=document.createElement('select');for(const [v,n]of pairs)s.add(new Option(n,v));s.value=value;l.append(s);return l;}function escapeText(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}

const designColorMap={designAccent:'accent',designInk:'ink',designBackground:'background',designMuted:'muted',designHeader:'header',designCard:'card',designBorder:'border'};
for(const [id,key] of Object.entries(designColorMap))$(id).oninput=e=>{design.colors[key]=e.target.value;persist();};
$('designFont').onchange=e=>{design.font=e.target.value;persist();};
$('designAnimations').onchange=e=>{design.animations=e.target.checked;persist();};
$('designHeaderSticky').onchange=e=>{design.ui.headerSticky=e.target.checked;persist();};
for(const [id,key] of [['designHeaderLayout','headerLayout'],['designLanguageStyle','languageStyle'],['designCardShadow','cardShadow']])$(id).onchange=e=>{design.ui[key]=e.target.value;persist();};
$('designButtonWeight').onchange=e=>{design.ui.buttonWeight=Number(e.target.value);persist();};
for(const [id,key] of [['designBodySize','bodySize'],['designH1Size','h1Size'],['designH2Size','h2Size'],['designHeaderHeight','headerHeight'],['designLogoWidth','logoWidth'],['designNavGap','navGap'],['designContainerWidth','containerWidth'],['designSectionGap','sectionGap'],['designButtonRadius','buttonRadius'],['designCardRadius','cardRadius']])$(id).oninput=e=>{design.ui[key]=Number(e.target.value);const out=$(id+'Value');if(out)out.textContent=e.target.value+' px';persist();};

$('addPage').onclick=()=>{let n=1,slug='new-page';while(data.pages.some(p=>p.slug===slug))slug='new-page-'+(++n);const p=blankPage(slug);data.pages.push(p);persist();renderPageList();selectPage(p.id);};
$('addReviewsPage').onclick=()=>{let p=data.pages.find(x=>x.slug==='reviews');if(!p){p=blankPage('reviews');p.title.en='Customer Reviews';p.navLabel.en='Reviews';const b=blankPageBlock('reviews');b.title.en='What customers say';b.body.en='Customer feedback from NOODY.AI services and products.';b.limit=30;p.blocks=[b];data.pages.push(p);persist();renderPageList();}selectPage(p.id);};
$('pageLanguage').onchange=()=>{renderPageLanguage();renderBlocks();};$('pageSlug').onchange=e=>{const p=pageById(),v=e.target.value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');if(p.slug!=='home'&&v&&!data.pages.some(x=>x!==p&&x.slug===v)){p.slug=v;persist();renderPageList();$('openPageLink').href=pageHref(p);}else e.target.value=p.slug;};$('pageActive').onchange=e=>{pageById().active=e.target.checked;persist();renderPageList();};$('pageNav').onchange=e=>{pageById().showInNav=e.target.checked;persist();renderPageList();};for(const [id,key]of [['pageNavLabel','navLabel'],['pageTitle','title'],['pageMeta','metaDescription']])$(id).oninput=e=>{pageById()[key][$('pageLanguage').value]=e.target.value;persist();renderPageList();};$('addBlock').onclick=()=>{const p=pageById(),b=blankPageBlock($('newBlockType').value);if(b.type==='whatsappCta'){b.title.en='Need help choosing?';b.body.en='Chat with NOODY.AI on WhatsApp.';b.ctaLabel.en='Enquire on WhatsApp';}p.blocks.push(b);persist();renderBlocks();};$('deletePage').onclick=()=>{const p=pageById();if(!p||p.slug==='home')return;if(!confirm('Delete this page?'))return;data.pages=data.pages.filter(x=>x.id!==p.id);selectedPage='';$('pageEditor').classList.add('hidden');persist();renderPageList();loadHomePreview();};$('copyPageLink').onclick=()=>navigator.clipboard?.writeText(pageHref(pageById()));

function addItem(kind){const i=blankItem(kind,'AGATTI');i.name=kind==='SERVICE'?'New service':'New product';i.category=kind==='SERVICE'?'Services':'Products';i.categoryLabel.en=i.category;i.title.en=i.name;data.items.push(i);persist();renderItemList();selectItem(i.id);}$('addService').onclick=()=>addItem('SERVICE');$('addProduct').onclick=()=>addItem('PRODUCT');
for(const [id,key]of [['itemKind','kind'],['itemIsland','islandCode'],['itemName','name'],['itemCategory','category']])$(id).oninput=e=>{const i=itemById();i[key]=e.target.value;persist();renderItemList();};$('itemActive').onchange=e=>{itemById().active=e.target.checked;persist();renderItemList();};$('itemLanguage').onchange=()=>renderItemLanguage();for(const [id,key]of [['itemTitle','title'],['itemCategoryLabel','categoryLabel'],['itemPriceLabel','priceLabel'],['itemAvailabilityLabel','availabilityLabel'],['itemSummary','summary'],['itemDescription','description']])$(id).oninput=e=>{const i=itemById(),l=$('itemLanguage').value;i[key]??=langMap();i[key][l]=e.target.value;if(l==='en'&&key==='categoryLabel')i.category=i.category||e.target.value;if(l==='en'&&key==='priceLabel')i.priceText=e.target.value;if(l==='en'&&key==='availabilityLabel')i.availabilityText=e.target.value;persist();renderItemList();};
$('itemPhotoUpload').onchange=async e=>{try{await addUploadedMedia([...e.target.files]);const i=itemById();for(const m of data.media.slice(-e.target.files.length))i.photos.push({src:m.src,alt:langMap()});e.target.value='';persist();renderItemPhotos();}catch(err){status(err.message,true);}};$('addItemMedia').onclick=()=>{const i=itemById(),src=$('itemMediaSelect').value;if(src&&!i.photos.some(p=>p.src===src)){i.photos.push({src,alt:langMap()});persist();renderItemPhotos();}};$('addDetail').onclick=()=>{itemById().details.push({id:uuid(),label:langMap(),value:langMap()});persist();renderDetails();};$('addDetailPreset').onclick=()=>{const i=itemById(),labels=i.kind==='PRODUCT'?['Variant / Type','Weight / Size','Ingredients / Material','Made in / Origin','Packaging','Shelf life / Care','Pickup / Delivery']:['Duration','Service time','Location / Meeting point','Suitable for','Age / Fitness guidance','Group size / Capacity','Included','Not included','What to bring','Clothing / Equipment','Safety / Medical guidance','Weather note','Pickup / Transfer','Languages / Guide','Accessibility','Advance notice / Booking note','Cancellation / Reschedule note','Special notes'];const have=new Set(i.details.map(d=>(d.label.en||'').toLowerCase()));for(const label of labels)if(!have.has(label.toLowerCase()))i.details.push({id:uuid(),label:{en:label,ml:'',hi:''},value:langMap()});persist();renderDetails();};$('addItemSection').onclick=()=>{itemById().blocks.push({id:uuid(),style:'section',title:langMap(),body:langMap()});persist();renderItemSections();};$('addReview').onclick=()=>{itemById().reviews.push({id:uuid(),firstName:'Customer',stars:5,comment:'',commentText:langMap(),date:'',verified:false});persist();renderReviews();};$('deleteItem').onclick=()=>{const i=itemById();if(!i||!confirm('Delete this website item? Core Software is not affected.'))return;data.items=data.items.filter(x=>x.id!==i.id);selectedItem='';$('itemEditor').classList.add('hidden');persist();renderItemList();loadHomePreview();};$('copyItemLink').onclick=()=>navigator.clipboard?.writeText($('itemLink').value);

$('mediaUpload').onchange=async e=>{try{await addUploadedMedia([...e.target.files]);e.target.value='';}catch(err){status(err.message,true);}};$('addMediaUrl').onclick=()=>{try{const src=photoUrl($('mediaUrl').value.trim());data.media.push({id:uuid(),src,title:{en:'Image',ml:'',hi:''}});$('mediaUrl').value='';persist();renderMedia();}catch(err){status(err.message,true);}};
$('settingsLanguage').onchange=renderSettings;$('brandName').oninput=e=>{data.brand.name=e.target.value;persist();};$('brandTagline').oninput=e=>{data.brand.tagline[$('settingsLanguage').value]=e.target.value;persist();};$('brandLogo').onchange=e=>{data.brand.logo=e.target.value;persist();};$('whatsappNumber').oninput=e=>{data.whatsappNumber=e.target.value.replace(/\D/g,'');persist();};$('footerText').oninput=e=>{data.footer.text[$('settingsLanguage').value]=e.target.value;persist();};$('showPrivacy').onchange=e=>{data.footer.showPrivacy=e.target.checked;persist();};

function loadHomePreview(){previewMode='page';selectedPage=data.pages.find(p=>p.slug==='home')?.id||'';loadPagePreview();}function loadPagePreview(){const p=pageById();if(!p)return;previewReady=false;designPreviewReady=false;const u=new URL(p.slug==='home'?'./':'./page.html',location.href);if(p.slug!=='home')u.searchParams.set('slug',p.slug);u.searchParams.set('studio_preview','1');u.searchParams.set('design_preview','1');$('preview').src=u.href;}function loadItemPreview(){const i=itemById();if(!i)return;previewReady=false;designPreviewReady=false;const u=new URL(itemLink(i,location.href));u.searchParams.set('studio_preview','1');u.searchParams.set('design_preview','1');$('preview').src=u.href;}
function renderPreview(){try{if(previewReady){if(previewMode==='page')$('preview').contentWindow.postMessage({type:'NOODY_STUDIO_PAGE_PREVIEW',data,pageId:selectedPage,assets,language:$('pageLanguage').value},location.origin);else $('preview').contentWindow.postMessage({type:'NOODY_STUDIO_ITEM_PREVIEW',data,itemId:selectedItem,assets,language:$('itemLanguage').value},location.origin);}if(designPreviewReady)$('preview').contentWindow.postMessage({type:'NOODY_DESIGN_PREVIEW',design,language:previewMode==='page'?$('pageLanguage').value:$('itemLanguage').value},location.origin);}catch{}}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==$('preview').contentWindow)return;if(['NOODY_STUDIO_PAGE_READY','NOODY_STUDIO_ITEM_READY'].includes(e.data?.type)){previewReady=true;renderPreview();}if(e.data?.type==='NOODY_DESIGN_READY'){designPreviewReady=true;renderPreview();}});

async function download(openPublish=false){try{const valid=validateWebsiteData(data),validDesign=validateDesign(design),files={'website-data.json':JSON.stringify(valid,null,2)+'\n','site-design.json':JSON.stringify(validDesign,null,2)+'\n'};for(const [path,url]of Object.entries(assets)){if(!url.startsWith('data:image/webp;base64,'))continue;const binary=atob(url.split(',')[1]);files[path.slice(2)]=Uint8Array.from(binary,c=>c.charCodeAt(0));}const blob=makeZip(files),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='noody-website-update.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status(openPublish?'Publish package ready. GitHub publish screen opened.':'Website backup downloaded.');if(openPublish)setTimeout(()=>window.open('https://github.com/brownnoodyai-sketch/brownnoodyai-sketch.github.io/upload/main','_blank','noopener'),250);}catch(err){status('Cannot publish yet: '+err.message,true);}}$('download2').onclick=()=>download(false);$('saveTop').onclick=()=>saveNow('Website');$('saveBottom').onclick=()=>saveNow('Website');$('savePage').onclick=()=>saveNow('Page');$('saveItem').onclick=()=>saveNow('Service / Product');$('publishTop').onclick=()=>{if(saveNow('Website'))download(true);};$('publishBottom').onclick=()=>{if(saveNow('Website'))download(true);};$('reloadPublished').onclick=()=>{localStorage.removeItem(draftKey);location.reload();};

try{const saved=localStorage.getItem(draftKey);if(saved){const parsed=JSON.parse(saved);data=validateWebsiteData(parsed.data);design=validateDesign(parsed.design||DEFAULT_DESIGN);assets=parsed.assets||{};status('Restored Studio Pro draft.');}else{const [dataResponse,designResponse]=await Promise.all([fetch('./website-data.json',{cache:'no-store'}),fetch('./site-design.json',{cache:'no-store'})]);data=validateWebsiteData(await dataResponse.json());design=designResponse.ok?validateDesign(await designResponse.json()):structuredClone(DEFAULT_DESIGN);status('Published website and design loaded.');}}catch(err){status('Could not load website data/design: '+err.message,true);throw err;}
data.media??=[];renderPageList();renderItemList();renderMedia();renderDesign();renderSettings();tab('pages');selectPage(data.pages.find(p=>p.slug==='home').id);document.body.dataset.state='ready';