import {validateWebsiteData,blankItem,LANGUAGES,ISLAND_NAMES,localize,photoUrl} from './website-data.mjs';import {itemLink} from './listing.mjs';import {makeZip} from './zip.mjs';
const $=id=>document.getElementById(id),draftKey='noody.website.fullbuilder.v1';let data=null,selected=null,assets={},previewReady=false;
const status=(m,e=false)=>{$('status').textContent=m;$('status').classList.toggle('error',e);};
const emptyLang=()=>({en:'',ml:'',hi:''});
function uuid(){return crypto.randomUUID();}
function save(){try{data=validateWebsiteData(data);localStorage.setItem(draftKey,JSON.stringify({data,assets}));status('Draft saved on this device.');renderList();renderPreview();}catch(e){status(e.message,true);}}
function current(){return data?.items.find(i=>i.id===selected)||null;}
function linkFor(item){return itemLink(item,location.href);}
function renderTabs(name){for(const b of document.querySelectorAll('[data-tab]'))b.classList.toggle('active',b.dataset.tab===name);$('catalogueTab').classList.toggle('hidden',name!=='catalogue');$('homeTab').classList.toggle('hidden',name!=='home');$('settingsTab').classList.toggle('hidden',name!=='settings');if(name==='home')renderHomeBlocks();}
function renderList(){const box=$('items');box.replaceChildren();for(const item of data.items){const row=document.createElement('div');row.className='item-row'+(item.id===selected?' active':'');const title=document.createElement('strong');title.textContent=(item.kind==='SERVICE'?'🌊 ':'🎁 ')+(localize(item.title,'en',item.name)||item.name);const meta=document.createElement('div');meta.className='note';meta.textContent=ISLAND_NAMES[item.islandCode]+' · '+item.category+' · '+(item.active?'LIVE':'HIDDEN');const open=document.createElement('button');open.textContent='Edit';open.onclick=()=>selectItem(item.id);row.append(title,meta,open);box.append(row);}if(!data.items.length){const p=document.createElement('p');p.className='note';p.textContent='No website services/products yet. Add your first item.';box.append(p);}}
function selectItem(id){selected=id;const item=current();if(!item)return;$('itemEditor').classList.remove('hidden');$('kind').value=item.kind;$('island').value=item.islandCode;$('name').value=item.name;$('category').value=item.category;$('priceText').value=item.priceText;$('availabilityText').value=item.availabilityText;$('active').checked=item.active;$('publicLink').value=linkFor(item);$('openLink').href=linkFor(item);renderLanguage();renderPhotos();renderBlocks();renderReviews();renderList();const u=new URL(linkFor(item));u.searchParams.set('studio_preview','1');$('preview').src=u.href;document.body.dataset.selection='ready';}
function renderLanguage(){const item=current();if(!item)return;const lang=$('language').value;$('title').value=item.title[lang]||'';$('summary').value=item.summary[lang]||'';$('description').value=item.description[lang]||'';renderBlocks();}
function renderPhotos(){const item=current(),box=$('photos');box.replaceChildren();item.photos.forEach((p,i)=>{const d=document.createElement('div');d.className='photo';const img=document.createElement('img');img.src=assets[p.src]||p.src;img.alt=localize(p.alt,'en','Photo');const lang=$('language').value,alt=document.createElement('input');alt.placeholder='Photo description ('+lang+')';alt.value=p.alt[lang]||'';alt.oninput=()=>{p.alt[lang]=alt.value;save();};const actions=document.createElement('div');actions.className='actions';const cover=document.createElement('button');cover.textContent=i?'Make cover':'Cover';cover.disabled=!i;cover.onclick=()=>{item.photos.splice(i,1);item.photos.unshift(p);renderPhotos();save();};const remove=document.createElement('button');remove.textContent='Remove';remove.onclick=()=>{item.photos.splice(i,1);delete assets[p.src];renderPhotos();save();};actions.append(cover,remove);d.append(img,alt,actions);box.append(d);});}
function blockEditor(block,i,list,rerender){const d=document.createElement('div');d.className='photo';const top=document.createElement('div');top.className='actions';const style=document.createElement('select');for(const [v,l] of [['section','Normal'],['highlight','Highlight'],['note','Note / warning'],['steps','Steps / itinerary']])style.add(new Option(l,v));style.value=block.style;style.onchange=()=>{block.style=style.value;save();};const up=document.createElement('button');up.textContent='↑';up.disabled=i===0;up.onclick=()=>{[list[i-1],list[i]]=[list[i],list[i-1]];rerender();save();};const down=document.createElement('button');down.textContent='↓';down.disabled=i===list.length-1;down.onclick=()=>{[list[i+1],list[i]]=[list[i],list[i+1]];rerender();save();};const rm=document.createElement('button');rm.textContent='Remove';rm.onclick=()=>{list.splice(i,1);rerender();save();};top.append(style,up,down,rm);const lang=$('language').value,title=document.createElement('input');title.placeholder='Section title ('+lang+')';title.value=block.title[lang]||'';title.maxLength=300;title.oninput=()=>{block.title[lang]=title.value;save();};const body=document.createElement('textarea');body.rows=5;body.placeholder='Section content ('+lang+')';body.value=block.body[lang]||'';body.maxLength=10000;body.oninput=()=>{block.body[lang]=body.value;save();};d.append(top,title,body);return d;}
function renderBlocks(){const item=current(),box=$('blocks');if(!item||!box)return;box.replaceChildren();item.blocks.forEach((b,i)=>box.append(blockEditor(b,i,item.blocks,renderBlocks)));}
function renderHomeBlocks(){const box=$('homeBlocks');box.replaceChildren();data.homepageBlocks.forEach((b,i)=>box.append(blockEditor(b,i,data.homepageBlocks,renderHomeBlocks)));}
function renderReviews(){const item=current(),box=$('reviews');box.replaceChildren();item.reviews.forEach((r,i)=>{const d=document.createElement('div');d.className='photo';const row=document.createElement('div');row.className='row';const name=document.createElement('input');name.placeholder='First name';name.value=r.firstName;name.oninput=()=>{r.firstName=name.value;save();};const stars=document.createElement('select');for(let n=1;n<=5;n++)stars.add(new Option(n+' / 5',String(n)));stars.value=String(r.stars);stars.onchange=()=>{r.stars=Number(stars.value);save();};row.append(name,stars);const comment=document.createElement('textarea');comment.rows=3;comment.placeholder='Review';comment.value=r.comment;comment.oninput=()=>{r.comment=comment.value;save();};const row2=document.createElement('div');row2.className='row';const date=document.createElement('input');date.type='date';date.value=r.date||'';date.oninput=()=>{r.date=date.value;save();};const verified=document.createElement('label');verified.innerHTML='<input type="checkbox"> Verified customer';verified.querySelector('input').checked=r.verified;verified.querySelector('input').onchange=e=>{r.verified=e.target.checked;save();};row2.append(date,verified);const rm=document.createElement('button');rm.textContent='Remove review';rm.onclick=()=>{item.reviews.splice(i,1);renderReviews();save();};d.append(row,comment,row2,rm);box.append(d);});}
function renderSettings(){$('whatsappNumber').value=data.whatsappNumber;for(const box of document.querySelectorAll('[data-island-toggle]'))box.checked=data.islands.find(i=>i.code===box.dataset.islandToggle)?.active??false;}
function renderPreview(){if(!previewReady||!selected)return;const item=current();if(!item)return;try{$('preview').contentWindow.postMessage({type:'NOODY_STUDIO_ITEM_PREVIEW',data,itemId:item.id,assets,language:$('language').value},location.origin);}catch{}}
function addItem(kind){const item=blankItem(kind,'AGATTI');item.name=kind==='SERVICE'?'New service':'New product';item.category=kind==='SERVICE'?'Services':'Products';item.title.en=item.name;data.items.push(item);selected=item.id;save();selectItem(item.id);}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>renderTabs(b.dataset.tab);
$('addService').onclick=()=>addItem('SERVICE');$('addProduct').onclick=()=>addItem('PRODUCT');
for(const id of ['kind','island','name','category','priceText','availabilityText'])$(id).oninput=()=>{const item=current();if(!item)return;item[id==='island'?'islandCode':id]=$(id).value;if(id==='name'&&!item.title.en)item.title.en=item.name;save();$('publicLink').value=linkFor(item);$('openLink').href=linkFor(item);};
$('active').onchange=()=>{current().active=$('active').checked;save();};$('language').onchange=()=>{renderLanguage();renderPhotos();renderPreview();};
for(const id of ['title','summary','description'])$(id).oninput=()=>{const item=current(),lang=$('language').value;item[id][lang]=$(id).value;save();};
$('addBlock').onclick=()=>{current().blocks.push({id:uuid(),style:'section',title:emptyLang(),body:emptyLang()});renderBlocks();save();};
$('addHomeBlock').onclick=()=>{data.homepageBlocks.push({id:uuid(),style:'section',title:emptyLang(),body:emptyLang()});renderHomeBlocks();save();};
$('addReview').onclick=()=>{current().reviews.push({id:uuid(),firstName:'Customer',stars:5,comment:'',date:'',verified:false});renderReviews();save();};
$('photoUpload').onchange=async()=>{const item=current(),files=[...$('photoUpload').files];$('photoUpload').value='';if(item.photos.length+files.length>30){status('Use up to 30 photos per item.',true);return;}try{for(const file of files){if(file.size>8*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('Use PNG/JPEG/WebP up to 8 MB.');const bitmap=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise(r=>canvas.toBlob(r,'image/webp',.82));if(!blob||blob.size>600000)throw Error('Photo could not be compressed.');const dataUrl=await new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(blob);});const src='./media/'+uuid()+'.webp';assets[src]=dataUrl;item.photos.push({src,alt:emptyLang()});}renderPhotos();save();}catch(e){status(e.message,true);}};
$('addPhotoUrl').onclick=()=>{try{const item=current();if(item.photos.length>=30)throw Error('Use up to 30 photos.');const src=photoUrl($('photoUrl').value.trim());item.photos.push({src,alt:emptyLang()});$('photoUrl').value='';renderPhotos();save();}catch(e){status(e.message,true);}};
$('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText($('publicLink').value);status('Page link copied.');}catch{status('Copy this link: '+$('publicLink').value);}};
$('deleteItem').onclick=()=>{const item=current();if(!item)return;if(!confirm('Delete this website item? Core Software is not affected.'))return;data.items=data.items.filter(i=>i.id!==item.id);selected=null;$('itemEditor').classList.add('hidden');$('preview').src='./';save();};
$('whatsappNumber').oninput=()=>{data.whatsappNumber=$('whatsappNumber').value.replace(/\D/g,'');save();};for(const box of document.querySelectorAll('[data-island-toggle]'))box.onchange=()=>{const island=data.islands.find(i=>i.code===box.dataset.islandToggle);island.active=box.checked;if(!box.checked)for(const item of data.items.filter(i=>i.islandCode===island.code))item.active=false;save();renderList();};
async function download(){try{const valid=validateWebsiteData(data),files={'website-data.json':JSON.stringify(valid,null,2)+'\n'};for(const [path,dataUrl] of Object.entries(assets)){if(!dataUrl.startsWith('data:image/webp;base64,'))continue;const binary=atob(dataUrl.split(',')[1]);files[path.slice(2)]=Uint8Array.from(binary,c=>c.charCodeAt(0));}const blob=makeZip(files),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='noody-website-update.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Downloaded. Extract and upload to GitHub, then Commit changes.');}catch(e){status(e.message,true);}}
$('downloadAll').onclick=download;$('downloadAll2').onclick=download;$('resetDraft').onclick=()=>{localStorage.removeItem(draftKey);location.reload();};
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==$('preview').contentWindow)return;if(e.data?.type==='NOODY_STUDIO_ITEM_READY'){previewReady=true;renderPreview();}if(e.data?.type==='NOODY_STUDIO_ITEM_APPLIED')document.body.dataset.previewApplied='true';});
try{const saved=localStorage.getItem(draftKey);if(saved){const parsed=JSON.parse(saved);data=validateWebsiteData(parsed.data);assets=parsed.assets||{};status('Restored your local website draft.');}else{const response=await fetch('./website-data.json',{cache:'no-store'});data=validateWebsiteData(await response.json());status('Published website data loaded.');}}catch(e){status('Could not load website data: '+e.message,true);data={schema:'noody.website.v1',whatsappNumber:'919446944562',islands:Object.keys(ISLAND_NAMES).map(code=>({code,name:ISLAND_NAMES[code],active:true})),homepageBlocks:[],items:[]};}
renderList();renderSettings();renderTabs('catalogue');