import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {readFile} from 'node:fs/promises';import {resolve,extname} from 'node:path';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {fixture} from './fixture.mjs';
const run=promisify(execFile),root=resolve('.');
const mime={'.html':'text/html','.mjs':'text/javascript','.json':'application/json'};
async function browserCheck({script,path='/',offline=false,mutate}){
 const data=fixture();if(mutate)mutate(data);let unavailable=offline,origin='';
 const server=createServer(async(req,res)=>{try{
  const pathname=new URL(req.url,'http://127.0.0.1').pathname;
  if(pathname==='/config.json'){res.setHeader('content-type','application/json');res.end(JSON.stringify({apiOrigin:origin,whatsappNumber:'919446944562'}));return;}
  if(pathname==='/v1/public/catalogue'){res.setHeader('content-type','application/json');res.statusCode=unavailable?503:200;res.end(JSON.stringify(data));return;}
  if(pathname==='/outage'){unavailable=true;res.end('ok');return;}
  if(pathname==='/remove'){data.items=[];res.end('ok');return;}
  if(pathname==='/browser-check.mjs'){res.setHeader('content-type','text/javascript');res.end("const check=async()=>{if(document.body.dataset.state==='loading'){setTimeout(check,40);return;}try{"+script+";const p=document.createElement('pre');p.id='browser-result';p.textContent='BROWSER_PASS';document.body.append(p);}catch(e){const p=document.createElement('pre');p.id='browser-result';p.textContent='BROWSER_FAIL:'+e.message;document.body.append(p);}};check();");return;}
  const file=resolve(root,pathname==='/'?'index.html':'.'+pathname);if(!file.startsWith(root+'/')){res.statusCode=404;res.end();return;}
  let bytes=await readFile(file);if(extname(file)==='.html')bytes=Buffer.from(bytes.toString().replace('</body>','<script type="module" src="/browser-check.mjs"></script></body>'));
  res.setHeader('content-type',mime[extname(file)]||'application/octet-stream');res.end(bytes);
 }catch{res.statusCode=404;res.end();}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;
 try{const {stdout}=await run(process.env.CHROMIUM_PATH||'/usr/bin/chromium',['--headless','--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-proxy-server','--dump-dom','--virtual-time-budget=15000',origin+path],{timeout:30000,maxBuffer:2000000});assert.match(stdout,/>BROWSER_PASS</,stdout.match(/BROWSER_FAIL[^<]*/)?.[0]||stdout.slice(-2000));}
 finally{server.closeAllConnections();await new Promise(r=>server.close(r));}
}
test('island-first product selection preserves animations, exact query detail and localized WhatsApp context',async()=>browserCheck({script:"if(document.querySelectorAll('[data-key]').length)throw Error('island not selected');if(!document.querySelector('.bird-trail'))throw Error('animation removed');document.querySelector('[data-island=Agatti]').click();if(!document.getElementById('typeModal').classList.contains('open'))throw Error('type modal');document.querySelector('[data-kind=Products]').click();if(document.querySelectorAll('[data-key]').length!==1)throw Error('product filter');const detail=new URL(document.querySelector('[data-detail]').href);if(detail.pathname!=='/item.html'||detail.searchParams.get('kind')!=='PRODUCT'||detail.searchParams.get('island')!=='AGATTI')throw Error('detail identity');const language=document.getElementById('language');language.value='ml';language.dispatchEvent(new Event('change'));const text=new URL(document.querySelector('[data-enquiry]').href).searchParams.get('text');if(!text.includes('NOODY_ITEM:PRODUCT:22222222')||!text.includes('NOODY_ISLAND:AGATTI')||!text.includes('വിശദാംശ'))throw Error('localized handoff');"}));
test('shared service page opens the exact Kadmat record with working share and enquiry controls',async()=>browserCheck({path:'/item.html?kind=SERVICE&id=11111111-1111-4111-8111-111111111111&island=KADMAT',script:"if(document.getElementById('itemName').textContent!=='Kayaking'||!document.getElementById('itemDescription').textContent.includes('Kadmat'))throw Error('wrong item');if(!document.getElementById('shareItem'))throw Error('share unavailable');const text=new URL(document.getElementById('itemEnquiry').href).searchParams.get('text');if(!text.includes('NOODY_ISLAND:KADMAT')||!text.includes('NOODY_ITEM:SERVICE:11111111'))throw Error('wrong enquiry');const page=new URL(text.split('Page: ')[1]);if(page.searchParams.get('island')!=='KADMAT')throw Error('share identity');"}));
test('catalogue outage keeps general enquiry and hides offers',async()=>browserCheck({offline:true,script:"if(document.body.dataset.state!=='unavailable'||document.querySelectorAll('[data-key]').length)throw Error('stale offers');if(new URL(document.getElementById('emptyEnquiry').href).hostname!=='wa.me')throw Error('missing fallback');if(!document.querySelector('[data-island=Agatti]').disabled)throw Error('unverified availability');"}));
test('refresh failure removes previously rendered listings and item enquiries',async()=>browserCheck({script:"document.querySelector('[data-island=Agatti]').click();document.querySelector('[data-kind=Services]').click();if(document.querySelectorAll('[data-key]').length!==1)throw Error('initial offer');await fetch('/outage');document.getElementById('refresh').click();await new Promise(resolve=>{const poll=()=>document.body.dataset.state==='loading'?setTimeout(poll,30):resolve();poll();});if(document.querySelectorAll('[data-key]').length||document.querySelector('[data-enquiry]'))throw Error('stale offer');if(new URL(document.getElementById('emptyEnquiry').href).searchParams.get('text').includes('NOODY_ITEM:'))throw Error('stale token');"}));
test('removed shared item clears detail, price and exact-item enquiry after refresh',async()=>browserCheck({path:'/item.html?kind=PRODUCT&id=22222222-2222-4222-8222-222222222222&island=AGATTI',script:"if(!document.getElementById('itemEnquiry'))throw Error('initial detail');await fetch('/remove');document.getElementById('refresh').click();await new Promise(resolve=>{const poll=()=>document.body.dataset.state==='loading'?setTimeout(poll,30):resolve();poll();});if(document.getElementById('itemEnquiry')||document.getElementById('itemPrice')||document.getElementById('shareItem'))throw Error('removed detail');if(new URL(document.getElementById('generalEnquiry').href).searchParams.get('text').includes('NOODY_ITEM:'))throw Error('stale item');"}));
test('hostile feed text stays literal and private fields are absent from cards',async()=>browserCheck({mutate:data=>{data.items[0].name='<img src=x onerror=window.catalogueXss=true>';data.items[0].vendorAmount=99;data.items[0].commissionAmount=20;},script:"document.querySelector('[data-island=Agatti]').click();document.querySelector('[data-kind=Services]').click();if(window.catalogueXss||document.querySelector('.card-body img'))throw Error('HTML injection');if(!document.querySelector('.card h3').textContent.includes('<img'))throw Error('literal name');if(document.getElementById('cards').textContent.includes('vendorAmount')||document.getElementById('cards').textContent.includes('commissionAmount'))throw Error('private fields');"}));

test('visual preview changes text safely, reorders sections, hides optional navigation and preserves catalogue identity',async()=>browserCheck({script:"const {applyDesign,DEFAULT_DESIGN}=await import('/design.mjs');applyDesign({...DEFAULT_DESIGN,colors:{...DEFAULT_DESIGN.colors,accent:'#123456'},order:['about','hero','explore','how'],hidden:['how'],text:{en:{hero1:'<img src=x onerror=window.designXss=true>'}}});if(document.querySelector('main').firstElementChild.id!=='about'||!document.getElementById('how').hidden)throw Error('layout');if(!document.querySelector('nav a[href=\"#how\"]').hidden)throw Error('hidden navigation');if(document.querySelector('[data-copy=hero1]').textContent!=='<img src=x onerror=window.designXss=true>'||window.designXss)throw Error('unsafe text');if(getComputedStyle(document.documentElement).getPropertyValue('--design-accent')!=='#123456')throw Error('theme');document.querySelector('[data-island=Agatti]').click();document.querySelector('[data-kind=Products]').click();if(!new URL(document.querySelector('[data-enquiry]').href).searchParams.get('text').includes('NOODY_ITEM:PRODUCT:22222222'))throw Error('handoff changed');"}));
test('designer changes preview and survives reload as a device draft without publishing',async()=>browserCheck({path:'/designer.html',script:"const wait=async(predicate)=>{for(let n=0;n<100;n++){if(predicate())return;await new Promise(r=>setTimeout(r,40));}throw Error('preview timeout');};await wait(()=>document.body.dataset.previewApplied==='true');const color=document.querySelector('[data-color=accent]');color.value='#224488';color.dispatchEvent(new Event('input'));const text=document.querySelector('[data-text-key=hero1]');text.value='My island';text.dispatchEvent(new Event('input'));await wait(()=>document.getElementById('preview').contentDocument.querySelector('[data-copy=hero1]')?.textContent==='My island');const saved=JSON.parse(localStorage.getItem('noody.website.design.draft.v1'));if(saved.colors.accent!=='#224488'||saved.text.en.hero1!=='My island')throw Error('draft');document.getElementById('mobile').click();if(!document.getElementById('preview').classList.contains('mobile'))throw Error('mobile preview');if(document.getElementById('publishLink').href!=='https://github.com/brownnoodyai-sketch/brownnoodyai-sketch.github.io/upload/main')throw Error('publish location');"}));
test('live website ignores preview messages when opened directly',async()=>browserCheck({script:"await new Promise(r=>setTimeout(r,100));const original=document.querySelector('[data-copy=hero1]').textContent;window.postMessage({type:'NOODY_DESIGN_PREVIEW',design:{schema:'noody.design.v1',text:{en:{hero1:'Injected draft'}}}},location.origin);await new Promise(r=>setTimeout(r,100));if(document.querySelector('[data-copy=hero1]').textContent!==original)throw Error('draft reached production');"}));

test('listing editor writes three language fields, restores device draft and previews rich details safely',async()=>browserCheck({path:'/listing-editor.html',script:"const wait=async(predicate)=>{for(let n=0;n<150;n++){if(predicate())return;await new Promise(r=>setTimeout(r,40));}throw Error('preview timeout');};const listing=document.getElementById('listing');listing.value=[...listing.options].find(o=>o.textContent.includes('PRODUCT')).value;listing.dispatchEvent(new Event('change'));await wait(()=>document.body.dataset.selection==='ready');const description=document.querySelector('[data-field=description]');description.value='<img src=x onerror=window.listingXss=true> A handmade gift';description.dispatchEvent(new Event('input'));const highlights=document.querySelector('[data-field=highlights]');highlights.value='Made locally\\nGift packing available';highlights.dispatchEvent(new Event('input'));await wait(()=>document.getElementById('preview').contentDocument.getElementById('itemDescription')?.textContent.includes('handmade gift'));const child=document.getElementById('preview').contentWindow;if(child.listingXss||child.document.querySelector('#itemDescription img'))throw Error('unsafe details');if(!child.document.querySelector('[data-section=highlights]'))throw Error('missing highlights');const language=document.getElementById('language');language.value='ml';language.dispatchEvent(new Event('change'));const title=document.querySelector('[data-field=title]');title.value='ദ്വീപിലെ സമ്മാനം';title.dispatchEvent(new Event('input'));await wait(()=>child.document.getElementById('itemName')?.textContent==='ദ്വീപിലെ സമ്മാനം');const draft=JSON.parse(localStorage.getItem('noody.listing.draft.v1'));if(draft.content.text.ml.title!=='ദ്വീപിലെ സമ്മാനം'||!draft.content.text.en.description.includes('handmade gift'))throw Error('language overwrite');if(!new URL(child.document.getElementById('itemEnquiry').href).searchParams.get('text').includes('NOODY_ITEM:PRODUCT:22222222'))throw Error('canonical handoff');document.getElementById('mobile').click();if(!document.getElementById('preview').classList.contains('mobile'))throw Error('mobile preview');if(child.document.getElementById('verifiedReviews').textContent.includes('5 / 5'))throw Error('invented reviews');"}));
test('direct customer details ignore presentation drafts without an explicit parent preview',async()=>browserCheck({path:'/item.html?kind=PRODUCT&id=22222222-2222-4222-8222-222222222222&island=AGATTI',script:"const before=document.getElementById('itemName').textContent;const {blankContent}=await import('/listing-content.mjs');const content=blankContent({kind:'PRODUCT',id:'22222222-2222-4222-8222-222222222222',islandCode:'AGATTI'});content.text.en.title='Unpublished';window.postMessage({type:'NOODY_LISTING_PREVIEW',content},location.origin);await new Promise(r=>setTimeout(r,100));if(document.getElementById('itemName').textContent!==before)throw Error('draft published');"}));

test('uploaded product photos are compressed, previewed, reordered and removed without changing identity',async()=>browserCheck({path:'/listing-editor.html',script:"const wait=async(fn)=>{for(let n=0;n<150;n++){if(fn())return;await new Promise(r=>setTimeout(r,40));}throw Error('photo preview timeout');};const select=document.getElementById('listing');select.value=[...select.options].find(o=>o.textContent.includes('PRODUCT')).value;select.dispatchEvent(new Event('change'));await wait(()=>document.body.dataset.selection==='ready');const canvas=document.createElement('canvas');canvas.width=1600;canvas.height=1200;canvas.getContext('2d').fillRect(0,0,1600,1200);const blob=await new Promise(r=>canvas.toBlob(r,'image/png')),dt=new DataTransfer();dt.items.add(new File([blob],'photo.png',{type:'image/png'}));const upload=document.getElementById('photosUpload');upload.files=dt.files;upload.dispatchEvent(new Event('change'));await wait(()=>document.querySelectorAll('#photos .photo').length===1);await wait(()=>document.getElementById('preview').contentDocument.getElementById('galleryMain')?.src.startsWith('data:image/webp;'));const draft=JSON.parse(localStorage.getItem('noody.listing.draft.v1'));if(draft.content.photos.length!==1||!draft.content.photos[0].src.startsWith('./media/'))throw Error('published asset path');const child=document.getElementById('preview').contentDocument;if(child.getElementById('photoCount').textContent!=='1 / 1')throw Error('gallery count');document.querySelector('#photos .photo button:last-child').click();await wait(()=>!child.getElementById('galleryMain'));"}));
test('review form requires an invitation and does not invent a public submission',async()=>browserCheck({path:'/review.html',script:"if(!document.getElementById('reviewForm').hidden||document.body.dataset.state!=='unavailable')throw Error('unsigned review accepted');if(!document.getElementById('status').textContent.includes('completed NOODY order'))throw Error('missing instruction');"}));
