import test from 'node:test';import assert from 'node:assert/strict';
import {validateCatalogue,validateConfig,visibleItems,detailLink,parseDetail,enquiryLink,readPublicJson} from '../../catalogue.mjs';
const serviceId='11111111-1111-4111-8111-111111111111',productId='22222222-2222-4222-8222-222222222222';
export function fixture(){return {contract:'noody.public.v2',sourceId:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',revision:'a'.repeat(64),whatsappNumber:'919446944562',islands:[{code:'AGATTI',name:'Agatti',active:true},{code:'KADMAT',name:'Kadmat',active:true},{code:'KAVARATTI',name:'Kavaratti',active:false},{code:'KALPENI',name:'Kalpeni',active:false}],items:[{id:serviceId,kind:'SERVICE',islandCode:'AGATTI',name:'Kayaking',category:'Water Sports',description:'A lagoon session. Please confirm timing with NOODY.',price:'From ₹600',availability:'Available on enquiry',canonicalToken:'SERVICE:'+serviceId},{id:productId,kind:'PRODUCT',islandCode:'AGATTI',name:'Tuna pickle',category:'Local Products',description:'Ask about quantity, ingredients and delivery.',price:'Price on enquiry',availability:'Confirm stock on enquiry',canonicalToken:'PRODUCT:'+productId},{id:serviceId,kind:'SERVICE',islandCode:'KADMAT',name:'Kayaking',category:'Water Sports',description:'Kadmat session',price:'Price on enquiry',availability:'Available on enquiry',canonicalToken:'SERVICE:'+serviceId}]};}
test('live v2 services and products stay separate and island scoped',()=>{const c=validateCatalogue(fixture());assert.equal(visibleItems(c,{island:'AGATTI',kind:'SERVICE'}).length,1);assert.equal(visibleItems(c,{island:'AGATTI',kind:'PRODUCT'})[0].name,'Tuna pickle');assert.equal(visibleItems(c,{island:'KADMAT'}).length,1);assert.equal(visibleItems(c,{island:'AGATTI',query:' TUNA '}).length,1);});
test('canonical product and island survive a direct/share link round trip',()=>{const item=fixture().items[1],url=detailLink(item,'https://example.com/noody-ai/?private=hidden#old');assert.equal(new URL(url).search,'');assert.deepEqual(parseDetail(new URL(url).hash),{kind:'PRODUCT',id:productId,islandCode:'AGATTI'});assert.equal(parseDetail('#/product/not-a-uuid?island=AGATTI'),null);});
test('WhatsApp request includes precise bot token, source and island without sending an order',()=>{const item=fixture().items[1];const url=new URL(enquiryLink('919446944562','AGATTI',item,'en','https://example.com/noody-ai/'));assert.equal(url.origin,'https://wa.me');const text=url.searchParams.get('text');assert.match(text,/NOODY_ITEM:PRODUCT:22222222/);assert.match(text,/NOODY_ISLAND:AGATTI/);assert.match(text,/NOODY_SOURCE:WEBSITE/);assert.match(text,/Tuna pickle/);assert.match(text,/final price/);assert.equal(enquiryLink('919446944562','KADMAT',item),null);});
test('Malayalam and Hindi enquiries preserve the same exact operational token',()=>{for(const language of ['ml','hi']){const text=new URL(enquiryLink('919446944562','AGATTI',fixture().items[0],language)).searchParams.get('text');assert.match(text,/NOODY_ITEM:SERVICE:/);assert.match(text,language==='ml'?/വിശദാംശ/ : /जानकारी/);}});
test('private financial/provider fields are excluded from the public projection',()=>{const raw=fixture();raw.items[0].vendorAmount=500;raw.items[0].commission=100;raw.secret='never-public';const c=validateCatalogue(raw);assert.ok(!('secret' in c));assert.ok(!('vendorAmount' in c.items[0]));assert.ok(!('commission' in c.items[0]));});
test('inactive islands, duplicates and mismatched canonical identity fail closed',()=>{let raw=fixture();raw.items[0].islandCode='KAVARATTI';assert.throws(()=>validateCatalogue(raw),/ITEM_INVALID/);raw=fixture();raw.items.push(raw.items[0]);assert.throws(()=>validateCatalogue(raw),/ITEM_DUPLICATE/);raw=fixture();raw.items[0].canonicalToken='PRODUCT:'+serviceId;assert.throws(()=>validateCatalogue(raw),/ITEM_INVALID/);});
test('travel packages never become active public listings',()=>{const raw=fixture();raw.items[0].category='Travel Packages';assert.equal(validateCatalogue(raw).items.some(i=>i.islandCode==='AGATTI'&&i.kind==='SERVICE'),false);});
test('legacy or malformed feeds cannot overwrite the canonical catalogue',()=>{const raw=fixture();raw.contract='noody.public.v1';assert.throws(()=>validateCatalogue(raw),/CATALOGUE_INVALID/);assert.throws(()=>validateCatalogue({}),/CATALOGUE_INVALID/);raw.contract='noody.public.v2';raw.islands[0].code='__proto__';assert.throws(()=>validateCatalogue(raw),/ISLAND_INVALID/);});
test('public config requires safe HTTPS and a valid business phone',()=>{assert.equal(validateConfig({apiOrigin:'https://api.example.com',whatsappNumber:'919446944562'}).apiOrigin,'https://api.example.com');for(const apiOrigin of ['http://api.example.com','https://user:secret@api.example.com','https://api.example.com/path','https://127.0.0.1','https://api.internal'])assert.throws(()=>validateConfig({apiOrigin,whatsappNumber:'919446944562'}),/CONFIG_INVALID/);assert.equal(validateConfig({apiOrigin:'http://127.0.0.1:1234',whatsappNumber:'919446944562'},'http://127.0.0.1:1234').apiOrigin,'http://127.0.0.1:1234');});
test('unsupported phone and island cannot create WhatsApp links',()=>{assert.equal(enquiryLink('javascript:alert(1)','AGATTI'),null);assert.equal(enquiryLink('919446944562','__proto__'),null);});
test('streamed catalogue reads enforce size and HTTP failures',async()=>{assert.deepEqual(await readPublicJson(new Response(JSON.stringify({ok:true}))),{ok:true});await assert.rejects(readPublicJson(new Response('{}',{status:503})),/UNAVAILABLE/);await assert.rejects(readPublicJson(new Response('123456789'),5),/TOO_LARGE/);});
