import test from 'node:test';import assert from 'node:assert/strict';import {writeFile,mkdtemp,rm,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {blankContent,validateContent,validateContentIndex,updateContentIndex,localized,contentKey,photoUrl} from '../../listing-content.mjs';import {makeZip} from '../../zip.mjs';
const item={kind:'PRODUCT',id:'22222222-2222-4222-8222-222222222222',islandCode:'AGATTI'};
test('listing identity, languages, galleries and factual text remain bounded and isolated by island',()=>{
 const c=blankContent(item);c.text.ml.description='ദ്വീപിലെ സമ്മാനം';c.text.en.title='<script>literal text</script>';c.photos=[{src:'./media/one.webp',alt:{ml:'ചിത്രം'}}];
 const v=validateContent(c,item);assert.equal(localized(v,'hi','description'),'ദ്വീപിലെ സമ്മാനം');assert.equal(v.text.en.title,'<script>literal text</script>');assert.throws(()=>validateContent(c,{...item,islandCode:'KADMAT'}));assert.throws(()=>validateContent({...c,photos:Array(9).fill(c.photos[0])}));assert.throws(()=>validateContent({...c,text:{en:{summary:'x'.repeat(401)}}}));assert.throws(()=>photoUrl('javascript:alert(1)'));assert.throws(()=>photoUrl('./media/../config.json'));assert.throws(()=>photoUrl('https://127.0.0.1/a'));assert.throws(()=>photoUrl('https://user:password@example.com/a'));assert.equal(photoUrl('https://images.example.com/a.webp'),'https://images.example.com/a.webp');
});
test('index contains only presentation metadata and preserves other exact listings',()=>{
 const a=blankContent(item),b=blankContent({...item,islandCode:'KADMAT'});a.text.en.title='Gift';a.photos=[{src:'./media/gift.webp',alt:{}}];let index={schema:'noody.listing-index.v1',entries:[]};index=updateContentIndex(updateContentIndex(index,b),a);assert.equal(index.entries.length,2);assert.equal(index.entries[1].path,'./listing-content/'+contentKey(a)+'.json');assert.equal(index.entries[1].cover.src,'./media/gift.webp');
 const raw=JSON.parse(JSON.stringify(index));raw.entries[0].path='https://evil.example/';raw.entries[0].price='fake';raw.entries[0].rating=5;const validated=validateContentIndex(raw);assert.equal(validated.entries[0].path,'./listing-content/'+contentKey(b)+'.json');assert.equal('price' in validated.entries[0],false);assert.equal('rating' in validated.entries[0],false);assert.throws(()=>validateContentIndex({...index,entries:[index.entries[0],index.entries[0]]}));
});
test('export is a real UTF-8 ZIP with unchanged binary media and safe publication paths',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'noody-export-'));try{const text='Malayalam: മലയാളം · हिन्दी',image=Uint8Array.from([0,1,255,128,45]);const zip=makeZip({'listing-content.json':text,'media/photo.webp':image});await writeFile(join(dir,'update.zip'),new Uint8Array(await zip.arrayBuffer()));const run=promisify(execFile);await run('unzip',['-t',join(dir,'update.zip')]);await run('unzip',['-q',join(dir,'update.zip'),'-d',join(dir,'out')]);assert.equal(await readFile(join(dir,'out/listing-content.json'),'utf8'),text);assert.deepEqual(new Uint8Array(await readFile(join(dir,'out/media/photo.webp'))),image);assert.throws(()=>makeZip({'../config.json':'bad'}));}finally{await rm(dir,{recursive:true,force:true});}
});
